insert into Persona(nome,cognome,email,password,ruolo,data_nascita) values('Mario','Rossi','m.rossi@gmail.com','123456',1,'1990-01-01');
insert into Persona(nome,cognome,email,password,ruolo,data_nascita) values('Pasquale','Bianchi','p.bianchi@gmail.com','123456',1,'1980-01-01');
insert into Persona(nome,cognome,email,password,ruolo,data_nascita) values('Luigi','Rossi','l.rossi@gmail.com','123456',0,'1995-01-01');
insert into Persona(nome,cognome,email,password,ruolo,data_nascita) values('Ciro','Esposito','c.esposito@gmail.com','123456',0,'1970-01-01');
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Mazda','CX-1',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Mazda','CX-2',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Mazda','CX-3',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Mazda','CX-4',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Mazda','CX-5',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Mazda','CX-6',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Mazda','CX-7',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Mazda','CX-8',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Mazda','CX-9',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Mazda','CX-10',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Fiat','CX-1',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Fiat','CX-2',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Fiat','CX-3',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Fiat','CX-4',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Fiat','CX-5',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Fiat','CX-6',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Fiat','CX-7',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Fiat','CX-8',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Fiat','CX-9',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Fiat','CX-10',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Opel','AX-1',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Opel','AX-2',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Opel','AX-3',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Opel','AX-4',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Opel','AX-5',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Opel','AX-6',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Opel','AX-7',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Opel','AX-8',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Opel','AX-9',2019,'Un carro di test',3,1);
insert into Autovettura(marca,modello,anno_di_immatricolazione,descrizione,persona_fk,version) values('Opel','AX-10',2019,'Un carro di test',3,1);
